### ISSUE TITLE
Build failed for shard

### ISSUE THREAD

**Issue by miketheman** [barisbalic/crystal-docs#2]
https://crystal-docs.org/miketheman/statsd.cr/

> BUILD FAILED
> WE COULDN'T BUILD THE DOCUMENTATION YOU WERE LOOKING FOR…
> We couldn't build the documentation for this Shard. If you can build it locally then please raise an issue with us so that we can look into it. If it doesn't build locally, consider raising an issue with the author.

**Comment by barisbalic** [comment]
Hi @miketheman thanks for pointing this out, looks like docker has eaten up an incredible amount of inode capacity, I don't know exactly how to fix this, I'm not sure what is/isn't safe to delete when it comes to docker, so I'll do some research a bit later today and either fix it, or move to a bigger instance.  I'll update you as soon as this is fixed.

**Comment by barisbalic** [comment]
@miketheman sorry for the delay, busy time, and it's not something I was familiar with.  I've remedied the problem for now and am in the process of triggering all of the doc rebuilds.  Thank you very much for bringing this up, I'll close this issue once all of the docs are built.

**Comment by barisbalic** [comment]
I've rebuilt all the docs, a few projects are not building because they require a crystal version pre 0.18.6 which I feel should probably be left as they are, given they are not being maintained.  A couple of builds failed for new and probably uninteresting reasons, but I'll look into them individually on the weekend.  Again thanks very much for reporting the problem, please feel free to comment further but I'll close this issue for now.

**Comment by miketheman** [comment]
@barisbalic Thank you for your prompt attention in handling this!
